[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-images.jpeg
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-images.jpeg
GtkTheme=oomox-images.jpeg
IconTheme=oomox-images.jpeg
MetacityTheme=oomox-images.jpeg
