# Shell variables
# Generated by 'wal'
wallpaper='/home/brandon/Wallpaper/images.jpeg'

# Special
background='#0e030f'
foreground='#f1adca'
cursor='#f1adca'

# Colors
color0='#0e030f'
color1='#4C1B44'
color2='#6B1A48'
color3='#4E2547'
color4='#6F254E'
color5='#982457'
color6='#CF316D'
color7='#f1adca'
color8='#a8798d'
color9='#4C1B44'
color10='#6B1A48'
color11='#4E2547'
color12='#6F254E'
color13='#982457'
color14='#CF316D'
color15='#f1adca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
