--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/brandon/Wallpaper/images.jpeg"

-- Special
background="#0e030f"
foreground="#f1adca"
cursor="#f1adca"

-- Colors
color0="#0e030f"
color1="#4C1B44"
color2="#6B1A48"
color3="#4E2547"
color4="#6F254E"
color5="#982457"
color6="#CF316D"
color7="#f1adca"
color8="#a8798d"
color9="#4C1B44"
color10="#6B1A48"
color11="#4E2547"
color12="#6F254E"
color13="#982457"
color14="#CF316D"
color15="#f1adca"
